name: Benchmark

on:
  - push
  - pull_request

jobs:
  benchmark:
    name: "Benchmark: ${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install dependencies
        run: |
          bundle install
          gem install csv -v 3.0.1
          gem install csv -v 3.0.2
      - name: Benchmark
        run: |
          rake benchmark
